Fix ESM issue with webpack-css plugin
When we are using `size-limit` with` @size-limit/webpack-css` plugin `v10.0.1` we are having an issue and see this error running `size-limit` during plugin loading
```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'src/experiment
/size-limit-experiment/node_modules/@size-limit/webpack-css/package.json' contains \"type\": \"module\".
To treat it as a CommonJS script, rename it to use the '.cjs' file extension.\n
```

As a solution we use createRequire to require commonjs from esm module.

---

Also,
- adding webpack-css plugin as a workspace to global workspace package.json.
- checking that load-plugins() is not throwing an error when we load
  webpack-css
  (https://github.com/mendrew/size-limit/blob/f9e9a78c3f62be7061bfd25efa7e546f02de549c/packages/size-limit/test/load-plugins.test.js#L8-L16)